name: R-CMD-check

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - { os: ubuntu-latest,   r: 'devel' }
          - { os: ubuntu-latest,   r: 'release' }
          - { os: macOS-latest,    r: 'release' }
          - { os: windows-latest,  r: 'release' }

    steps:
      - uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}

      - name: Install dependencies
        run: |
          install.packages('devtools')
          devtools::install_deps(dependencies = TRUE)
          if (file.exists('tests/testthat.R')) {
            install.packages('testthat')
          }

      - name: Run R CMD check
        run: |
          devtools::check()
